const DasboardActions = {
  START_DASHBOARD_FETCHING: "START_DASHBOARD_FETCHING",
  DASHBOARD_FETCHING_SUCCESS: "DASHBOARD_FETCHING_SUCCESS",
  SET_DASHBOARD_IS_LOADING: "SET_DASHBOARD_IS_LOADING",
};

export default DasboardActions;
