const NotificationsActions = {
  START_NOTIFICATIONS_FETCHING: "START_NOTIFICATIONS_FETCHING",
  NOTIFICATIONS_FETCHING_SUCCESS: "NOTIFICATIONS_FETCHING_SUCCESS",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_NOTFICATION_IS_LOADING: "SET_NOTFICATION_IS_LOADING",
  SET_HAS_MORE: "SET_HAS_MORE",
  START_FETCH_UNVIEWED_NOTIFICATIONS_COUNT:
    "START_FETCH_UNVIEWED_NOTIFICATIONS_COUNT",
  SET_UNVIEWED_NOTIFICATIONS_COUNT: "SET_UNVIEWED_NOTIFICATIONS_COUNT",
  SET_ALL_NOTIFICATION_TO_VIEWED: "SET_ALL_NOTIFICATION_TO_VIEWED",
  ADD_NEW_NOTIFICATION: "ADD_NEW_NOTIFICATION",
};

export default NotificationsActions;
