const sponsoringActions = {
  START_SPONSORING_FETCHING: "START_SPONSORING_FETCHING",
  SPONSORING_FETCHING_SUCCESS: "SPONSORING_FETCHING_SUCCESS",
  START_CREATE_SPONSORING: "START_CREATE_SPONSORING",
  CREATE_SPONSORING_SUCCESS: "CREATE_SPONSORING_SUCCESS",
  START_DELETE_SPONSORING: "START_DELETE_SPONSORING",
  DELETE_SPONSORING_SUCCESS: "DELETE_SPONSORING",
  START_UPDATE_SPONSORING: "START_UPDATE_SPONSORING",
  UPDATE_SPONSORING_SUCCESS: "UPDATE_SPONSORING_SUCCESS",
  START_ONE_SPONSORING_FETCHING: "START_ONE_SPONSORING_FETCHING",
  ONE_SPONSORING_FETCHING_SUCCESS: "ONE_SPONSORING_FETCHING_SUCCESS",
  START_SPONSORING_VALIDATION_FETCHING: "START_SPONSORING_VALIDATION_FETCHING",
  SPONSORING_VALIDATION_FETCHING_SUCCESS:
    "SPONSORING_VALIDATION_FETCHING_SUCCESS",
  CREATE_SPONSORING_VALIDATION_START: "CREATE_SPONSORING_VALIDATION_START",
  CREATE_SPONSORING_VALIDATION_SUCCESS: "CREATE_SPONSORING_VALIDATION_SUCCESS",
  START_SPONSORING_UPDATE_VALIDATION: "START_SPONSORING_UPDATE_VALIDATION",
  UPDATE_SPONSORING_VALIDATION_SUCCESS: "UPDATE_SPONSORING_VALIDATION_SUCCESS",
  START_DELETE_SPONSORING_VALIDATION: "START_DELETE_SPONSORING_VALIDATION",
  DELETE_SPONSORING_VALIDATION_SUCCESS: "DELETE_SPONSORING_VALIDATION_SUCCESS",
};

export default sponsoringActions;
