const IntervenantActions = {
  START_INTERVENANT_FETCHING: "START_INTERVENANT_FETCHING",
  INTERVENANT_FETCHING_SUCCESS: "INTERVENANT_FETCHING_SUCCESS",
  START_CREATE_INTERVENANT: "START_CREATE_INTERVENANT",
  CREATE_INTERVENANT_SUCCESS: "CREATE_INTERVENANT_SUCCESS",
  START_DELETE_INTERVENANT: "START_DELETE_INTERVENANT",
  DELETE_INTERVENANT_SUCCESS: "DELETE_INTERVENANT",
  START_UPDATE_INTERVENANT: "START_UPDATE_INTERVENANT",
  UPDATE_INTERVENANT_SUCCESS: "UPDATE_INTERVENANT_SUCCESS",
};

export default IntervenantActions;
