const IntervenantActions = {
  START_INTERVENANT_FETCHING: "START_INTERVENANT_FETCHING",
  INTERVENANT_FETCHING_SUCCESS: "INTERVENANT_FETCHING_SUCCESS",
  START_CREATE_INTERVENANT: "START_CREATE_INTERVENANT",
  CREATE_INTERVENANT_SUCCESS: "CREATE_INTERVENANT_SUCCESS",
  START_DELETE_INTERVENANT: "START_DELETE_INTERVENANT",
  DELETE_INTERVENANT_SUCCESS: "DELETE_INTERVENANT",
  START_UPDATE_INTERVENANT: "START_UPDATE_INTERVENANT",
  UPDATE_INTERVENANT_SUCCESS: "UPDATE_INTERVENANT_SUCCESS",
  START_ONE_INTERVENANT_FETCHING: "START_ONE_INTERVENANT_FETCHING",
  ONE_INTERVENANT_FETCHING_SUCCESS: "ONE_INTERVENANT_FETCHING_SUCCESS",
  START_INTERVENANT_VALIDATION_FETCHING:
    "START_INTERVENANT_VALIDATION_FETCHING",
  INTERVENANT_VALIDATION_FETCHING_SUCCESS:
    "INTERVENANT_VALIDATION_FETCHING_SUCCESS",
  CREATE_INTERVENANT_VALIDATION_START: "CREATE_INTERVENANT_VALIDATION_START",
  CREATE_INTERVENANT_VALIDATION_SUCCESS:
    "CREATE_INTERVENANT_VALIDATION_SUCCESS",
  START_INTERVENANT_UPDATE_VALIDATION: "START_INTERVENANT_UPDATE_VALIDATION",
  UPDATE_INTERVENANT_VALIDATION_SUCCESS:
    "UPDATE_INTERVENANT_VALIDATION_SUCCESS",
  START_DELETE_INTERVENANT_VALIDATION: "START_DELETE_INTERVENANT_VALIDATION",
  DELETE_INTERVENANT_VALIDATION_SUCCESS:
    "DELETE_INTERVENANT_VALIDATION_SUCCESS",
};

export default IntervenantActions;
