const evenemetActions = {
  START_DEMANDE_FETCHING: "START_DEMANDE_FETCHING",
  DEMANDE_FETCHING_SUCCESS: "DEMANDE_FETCHING_SUCCESS",
  START_ONE_DEMANDE_FETCHING: "START_ONE_DEMANDE_FETCHING",
  ONE_DEMANDE_FETCHING_SUCCESS: "ONE_DEMANDE_FETCHING_SUCCESS",
  DEMANDE_FETCHING_FAILURE: "DEMANDE_FETCHING_FAILURE",
  START_DEMANDE_CREACTION: "START_DEMANDE_CREACTION",
  DEMANDE_CREATION_SUCCESS: "DEMANDE_CREATION_SUCCESS",
  DEMANDE_CREATION_FAILURE: "DEMANDE_CREATION_FAILURE",
  START_DEMANDE_VALIDATION_FETCHING: "START_DEMANDE_VALIDATION_FETCHING",
  DEMANDE_VALIDATION_FETCHING_SUCCESS: "DEMANDE_VALIDATION_FETCHING_SUCCESS",
};

export default evenemetActions;
