const evenemetActions = {
  START_DEMANDE_FETCHING: "START_DEMANDE_FETCHING",
  DEMANDE_FETCHING_SUCCESS: "DEMANDE_FETCHING_SUCCESS",
  DEMANDE_FETCHING_FAILURE: "DEMANDE_FETCHING_FAILURE",
};

export default evenemetActions;
