const evenemetActions = {
  START_DEMANDE_FETCHING: "START_DEMANDE_FETCHING",
  DEMANDE_FETCHING_SUCCESS: "DEMANDE_FETCHING_SUCCESS",
  START_ONE_DEMANDE_FETCHING: "START_ONE_DEMANDE_FETCHING",
  ONE_DEMANDE_FETCHING_SUCCESS: "ONE_DEMANDE_FETCHING_SUCCESS",
  DEMANDE_FETCHING_FAILURE: "DEMANDE_FETCHING_FAILURE",
  START_DEMANDE_CREACTION: "START_DEMANDE_CREACTION",
  DEMANDE_CREATION_SUCCESS: "DEMANDE_CREATION_SUCCESS",
  DEMANDE_CREATION_FAILURE: "DEMANDE_CREATION_FAILURE",
  START_DEMANDE_VALIDATION_FETCHING: "START_DEMANDE_VALIDATION_FETCHING",
  DEMANDE_VALIDATION_FETCHING_SUCCESS: "DEMANDE_VALIDATION_FETCHING_SUCCESS",
  CREATE_VALIDATION_START: "CREATE_VALIDATION_START",
  CREATE_VALIDATION_SUCCESS: "CREATE_VALIDATION_START_SUCCESS",
  START_UPDATE_DEMANDE: "START_UPDATE_DEMANDE",
  UPDATE_DEMANDE_SUCCESS: "UPDATE_DEMANDE_SUCCESS",
  START_DELETE_DEMANDE: "START_DELETE_DEMANDE",
  DELETE_DEMANDE_SUCCESS: "DELETE_DEMANDE_SUCCESS",
  START_UPDATE_VALIDATION: "START_UPDATE_VALIDATION",
  UPDATE_VALIDATION_SUCCESS: "UPDATE_VALIDATION_SUCCESS",
};

export default evenemetActions;
