const BilanActions = {
  START_BILAN_FETCHING: "START_BILAN_FETCHING",
  BILAN_FETCHING_SUCCESS: "BILAN_FETCHING_SUCCESS",
  START_CREATE_BILAN: "START_CREATE_BILAN",
  CREATE_BILAN_SUCCESS: "CREATE_BILAN_SUCCESS",
  START_DELETE_BILAN: "START_DELETE_BILAN",
  DELETE_BILAN_SUCCESS: "DELETE_BILAN",
  START_UPDATE_BILAN: "START_UPDATE_BILAN",
  UPDATE_BILAN_SUCCESS: "UPDATE_BILAN_SUCCESS",
  START_ONE_BILAN_FETCHING: "START_ONE_BILAN_FETCHING",
  ONE_BILAN_FETCHING_SUCCESS: "ONE_BILAN_FETCHING_SUCCESS",
  START_VALIDATE_BILAN: "START_VALIDATE_BILAN",
  VALIDATE_BILAN_SUCCESS: "VALIDATE_BILAN_SUCCESS",
};

export default BilanActions;
