const UtilisateurActions = {
  START_UTILISATEUR_FETCHING: "START_UTILISATEUR_FETCHING",
  UTILISATEUR_FETCHING_SUCCESS: "UTILISATEUR_FETCHING_SUCCESS",
  START_CREATE_UTILISATEUR: "START_CREATE_UTILISATEUR",
  CREATE_UTILISATEUR_SUCCESS: "CREATE_UTILISATEUR_SUCCESS",
  START_DELETE_UTILISATEUR: "START_DELETE_UTILISATEUR",
  DELETE_UTILISATEUR_SUCCESS: "DELETE_UTILISATEUR",
  START_UPDATE_UTILISATEUR: "START_UPDATE_UTILISATEUR",
  UPDATE_UTILISATEUR_SUCCESS: "UPDATE_UTILISATEUR_SUCCESS",
  START_ONE_UTILISATEUR_FETCHING: "START_ONE_UTILISATEUR_FETCHING",
  ONE_UTILISATEUR_FETCHING_SUCCESS: "ONE_UTILISATEUR_FETCHING_SUCCESS",
};

export default UtilisateurActions;
